---
- hosts: all
  gather_facts: yes

  tasks: 
    - name: Install requests python package
      pip:
        name: requests
      vars:
        ansible_python_interpreter: /usr/bin/python3


    - name: stop the running container
      docker_container: 
        name: nginx-server
        state: stopped 
      ignore_errors: yes
    
    - name: remove  nginx container
      docker_container:
        name: nginx-server
        state: absent


    - name: remove  nginx image
      docker_image:
        name: nginx:latest
        state: absent

      

    - debug: 
        msg: "nginx container removed successfully"
